---
- name: Provision EC2 instance
  hosts: localhost
  vars:
      #ami-e4537381
      region:   us-east-2
      ami:      ami-daae8bbf
      set_dns:  False
      instance: t2.micro
      security_group: jenkinssg
  connection: local
  gather_facts: false
  tasks:
    - name: Launch instance
      ec2:
        keypair={{ keypair }}
        group={{ security_group }}
        aws_access_key={{ aws_access_key }}
        aws_secret_key={{ aws_secret_key }}
        instance_type={{ instance }}
        image={{ ami }}
        region={{ region }}
        wait=yes
      register: ec2
    - debug: var={{ item }}
      with_items: ec2.instances

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

    # - name: Add new instance to host group
    #   local_action: add_host hostname=item.public_dns_name
    #                 groupname=launched
    #   with_items: ec2.instances

    - name: Ensure DNS entry exists
      route53: command=create overwrite=yes
               record=ci.{{ dns_zone }} type=A zone={{ dns_zone }}
               value=item.public_ip
      with_items: ec2.instances
      when: set_dns
  
  # tasks:
  #   - name: Ensure Java is present
  #     yum: name={{ jenkins_jdk }} state=present
  #     when: ansible_distribution != 'Amazon'

  #   - name: Ensure Jenkins Yum repo present
  #     get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo
  #          dest=/etc/yum.repos.d/jenkins.repo mode=0644

  #   - name: Check for Jenkins GPG in rpmdb
  #     command: rpm -q {{ jenkins_key }}
  #     register: keycheck
  #     ignore_errors: true

  #   - name: Ensure Jenkins GPG key installed
  #     command: rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
  #     when: keycheck|failed

  #   - name: Ensure Jenkins installed
  #     yum: name=jenkins state=present

  #   - name: Ensure Jenkins is running
  #     service: name=jenkins state=running enabled=true
- include: RedHat.yml
